import { repo, transaction } from './db/repositories.js';
import { STORES } from './core/constants.js';
import { escapeHtml, nowISO } from './core/utils.js';
import { formatDate } from './core/dates.js';
import { toast } from './ui/toast.js';
import { emptyState, sectionHeader } from './ui/components.js';

const ANN_TYPES = [['summons','إعلان صحيفة دعوى'],['judgment','إعلان حكم'],['execution','إعلان تنبيه/تنفيذ'],['appeal','إعلان طعن'],['expert','إعلان خبير'],['other','أخرى']];
const ANN_STATUS = [['draft','مسودة'],['prepared','تم التجهيز'],['delivered','تم التسليم للمحضر'],['served','تم الإعلان'],['failed','تعذر الإعلان'],['cancelled','ملغى'],['other','أخرى']];
const METHODS = [['phone','هاتف'],['whatsapp','واتساب'],['sms','رسالة نصية'],['email','بريد إلكتروني'],['in-person','مقابلة شخصية'],['office','مراسلة المكتب'],['other','أخرى']];
const labelOf=(items,v)=>items.find(x=>x[0]===v)?.[1]||v||'—';
const val=(fd,n)=>String(fd.get(n)??'').trim();
const active=async s=>(await repo(s).all({ limit: 500 })).filter(x=>!x.archived);
const q=()=>new URLSearchParams((location.hash.split('?')[1]||'').split('#')[0]);
const qid=()=>Number(q().get('id'))||null;
const caseLabel=c=>`${c.caseNumber||'—'}/${c.caseYear||'—'} — ${c.subject||c.caseType||'قضية'}`;
function modal(title,content){const w=document.createElement('div');w.className='modal-backdrop';w.innerHTML=`<section class="modal work-modal" role="dialog" aria-modal="true"><div class="modal-header"><h2>${escapeHtml(title)}</h2><button class="icon-button" data-close type="button">×</button></div>${content}</section>`;const close=()=>w.remove();w.querySelector('[data-close]').onclick=close;w.addEventListener('click',e=>{if(e.target===w)close()});document.getElementById('modalRoot').appendChild(w);return{wrap:w,close};}
async function refs(){const [cases,clients,opponents,authorities]=await Promise.all([active(STORES.cases),active(STORES.clients),active(STORES.opponents),active(STORES.courtsAuthorities)]);return{cases,clients,opponents,authorities};}
const caseSelect=(xs,s)=>`<option value="">اختر القضية</option>`+xs.map(c=>`<option value="${c.id}" ${Number(c.id)===Number(s)?'selected':''}>${escapeHtml(caseLabel(c))}</option>`).join('');
const clientSelect=(xs,s)=>`<option value="">— بدون ربط —</option>`+xs.map(c=>`<option value="${c.id}" ${Number(c.id)===Number(s)?'selected':''}>${escapeHtml(c.fullName)}</option>`).join('');
const opponentSelect=(xs,s)=>`<option value="">— غير محدد —</option>`+xs.map(c=>`<option value="${c.id}" ${Number(c.id)===Number(s)?'selected':''}>${escapeHtml(c.name)}</option>`).join('');
const authoritySelect=(xs,s,type)=>`<option value="">— غير محدد —</option>`+xs.filter(a=>a.active!==false&&(!type||a.type===type)).map(a=>`<option value="${a.id}" ${Number(a.id)===Number(s)?'selected':''}>${escapeHtml(a.name)}${a.city?` — ${escapeHtml(a.city)}`:''}</option>`).join('');
const opts=(xs,s)=>xs.map(([v,l])=>`<option value="${v}" ${v===s?'selected':''}>${escapeHtml(l)}</option>`).join('');

function announcementForm(r,rs){return `<form id="announcementForm"><div class="form-grid">
<div class="field full"><label>القضية *</label><select class="select" name="caseId" required>${caseSelect(rs.cases,r.caseId)}</select></div>
<div class="field"><label>العميل</label><select class="select" name="clientId">${clientSelect(rs.clients,r.clientId)}</select></div>
<div class="field"><label>المعلن إليه/الخصم</label><select class="select" name="addresseeId">${opponentSelect(rs.opponents,r.addresseeId)}</select></div>
<div class="field"><label>نوع الإعلان</label><select class="select" name="type">${opts(ANN_TYPES,r.type||'other')}</select></div>
<div class="field"><label>الحالة</label><select class="select" name="status">${opts(ANN_STATUS,r.status||'draft')}</select></div>
<div class="field full"><label>عنوان الإعلان</label><input class="input" name="address" value="${escapeHtml(r.address||'')}" placeholder="العنوان المراد الإعلان فيه"></div>
<div class="field"><label>مكتب المحضرين</label><select class="select" name="processServerOfficeId">${authoritySelect(rs.authorities,r.processServerOfficeId,'processServerOffice')}</select></div>
<div class="field"><label>اسم المحضر</label><input class="input" name="bailiffName" value="${escapeHtml(r.bailiffName||'')}"></div>
<div class="field"><label>تاريخ إعداد الإعلان</label><input class="input" type="date" name="draftDate" value="${escapeHtml(r.draftDate||'')}"></div>
<div class="field"><label>تاريخ التسليم للمحضر</label><input class="input" type="date" name="deliveredDate" value="${escapeHtml(r.deliveredDate||'')}"></div>
<div class="field"><label>تاريخ الإعلان</label><input class="input" type="date" name="serviceDate" value="${escapeHtml(r.serviceDate||'')}"></div>
<div class="field"><label>رقم الإعلان</label><input class="input" name="announcementNumber" value="${escapeHtml(r.announcementNumber||'')}"></div>
<div class="field"><label>سنة الإعلان</label><input class="input" type="number" name="announcementYear" value="${escapeHtml(r.announcementYear||'')}"></div>
<div class="field full"><label>النتيجة</label><textarea class="textarea" name="result" rows="2">${escapeHtml(r.result||'')}</textarea></div>
<div class="field full"><label>تفاصيل النتيجة</label><textarea class="textarea" name="resultDetails" rows="3">${escapeHtml(r.resultDetails||'')}</textarea></div>
<div class="field full"><label>الإجراء التالي</label><input class="input" name="nextAction" value="${escapeHtml(r.nextAction||'')}"></div>
<div class="field full"><label>ملاحظات</label><textarea class="textarea" name="notes" rows="3">${escapeHtml(r.notes||'')}</textarea></div>
</div><div class="form-actions"><button class="primary-button" type="submit">حفظ</button><button class="secondary-button" type="button" data-close>إلغاء</button></div></form>`;}

async function saveAnnouncement(row,fd){const now=nowISO();const data={...row,caseId:Number(val(fd,'caseId')),clientId:val(fd,'clientId')?Number(val(fd,'clientId')):null,addresseeId:val(fd,'addresseeId')?Number(val(fd,'addresseeId')):null,type:val(fd,'type'),address:val(fd,'address'),courtId:null,processServerOfficeId:val(fd,'processServerOfficeId')?Number(val(fd,'processServerOfficeId')):null,bailiffName:val(fd,'bailiffName'),draftDate:val(fd,'draftDate'),deliveredDate:val(fd,'deliveredDate'),serviceDate:val(fd,'serviceDate'),announcementNumber:val(fd,'announcementNumber'),announcementYear:val(fd,'announcementYear')?Number(val(fd,'announcementYear')):null,status:val(fd,'status'),result:val(fd,'result'),resultDetails:val(fd,'resultDetails'),nextAction:val(fd,'nextAction'),notes:val(fd,'notes'),updatedAt:now};if(!data.caseId)throw new Error('القضية مطلوبة.');const c=await repo(STORES.cases).get(data.caseId);if(!c||c.archived)throw new Error('القضية غير موجودة أو مؤرشفة.');if(data.clientId){const x=await repo(STORES.clients).get(data.clientId);if(!x||x.archived)throw new Error('العميل غير موجود أو مؤرشف.');}if(data.addresseeId){const x=await repo(STORES.opponents).get(data.addresseeId);if(!x||x.archived)throw new Error('الخصم غير موجود أو مؤرشف.');}if(row.id)await repo(STORES.announcements).put(data);else{data.createdAt=now;data.id=await repo(STORES.announcements).add(data);}await repo(STORES.caseEvents).add({caseId:data.caseId,eventType:row.id?'announcement-updated':'announcement-created',eventDate:data.serviceDate||data.deliveredDate||data.draftDate||now.slice(0,10),title:row.id?'تعديل إعلان':'إضافة إعلان',description:`${labelOf(ANN_TYPES,data.type)} — ${data.result||'لم تسجل النتيجة'}`,sourceType:'announcement',sourceId:data.id,createdAt:now});}

export async function showAnnouncementForm(existing=null,afterSave=null){const rs=await refs();const {wrap,close}=modal(existing?'تعديل إعلان':'إضافة إعلان',announcementForm(existing||{},rs));wrap.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);wrap.querySelector('#announcementForm').addEventListener('submit',async e=>{e.preventDefault();try{await saveAnnouncement(existing||{},new FormData(e.currentTarget));close();toast(existing?'تم تحديث الإعلان.':'تم حفظ الإعلان.');afterSave?.();}catch(err){toast(err.message,'error')}});}

async function followUpForm(existing,kind,rs){const isContact=kind==='contact';return `<form id="communicationForm"><div class="form-grid">
<div class="field full"><label>القضية</label><select class="select" name="caseId">${caseSelect(rs.cases,existing.caseId)}</select></div>
<div class="field"><label>العميل</label><select class="select" name="clientId">${clientSelect(rs.clients,existing.clientId)}</select></div>
${isContact?`<div class="field"><label>الخصم</label><select class="select" name="opponentId">${opponentSelect(rs.opponents,existing.opponentId)}</select></div>`:''}
<div class="field"><label>التاريخ *</label><input class="input" type="date" name="date" value="${escapeHtml(existing.date||'')}" required></div>
<div class="field"><label>طريقة التواصل</label><select class="select" name="method">${opts(METHODS,existing.method||'phone')}</select></div>
<div class="field"><label>الشخص</label><input class="input" name="person" value="${escapeHtml(existing.person||'')}"></div>
<div class="field full"><label>الموضوع *</label><input class="input" name="subject" value="${escapeHtml(existing.subject||'')}" required></div>
<div class="field full"><label>النتيجة</label><textarea class="textarea" name="result" rows="3">${escapeHtml(existing.result||'')}</textarea></div>
<div class="field full"><label>الإجراء التالي</label><input class="input" name="${isContact?'nextAction':'nextDate'}" value="${escapeHtml(existing[isContact?'nextAction':'nextDate']||'')}" ${isContact?'':'type="date"'}></div>
<div class="field full"><label>ملاحظات</label><textarea class="textarea" name="notes" rows="3">${escapeHtml(existing.notes||'')}</textarea></div>
</div><div class="form-actions"><button class="primary-button" type="submit">حفظ</button><button class="secondary-button" type="button" data-close>إلغاء</button></div></form>`;}

async function saveCommunication(row,fd,kind){const now=nowISO(),isContact=kind==='contact';const data={...row,caseId:val(fd,'caseId')?Number(val(fd,'caseId')):null,clientId:val(fd,'clientId')?Number(val(fd,'clientId')):null,date:val(fd,'date'),method:val(fd,'method'),person:val(fd,'person'),subject:val(fd,'subject'),result:val(fd,'result'),notes:val(fd,'notes'),createdAt:row.createdAt||now,updatedAt:now};if(isContact){data.opponentId=val(fd,'opponentId')?Number(val(fd,'opponentId')):null;data.nextAction=val(fd,'nextAction');}else data.nextDate=val(fd,'nextDate')||null;if(!data.date||!data.subject)throw new Error('التاريخ والموضوع مطلوبان.');const store=isContact?STORES.contacts:STORES.followUps;if(row.id)await repo(store).put(data);else data.id=await repo(store).add(data);if(data.caseId)await repo(STORES.caseEvents).add({caseId:data.caseId,eventType:isContact?'contact':'follow-up',eventDate:data.date,title:isContact?'تسجيل اتصال':'تسجيل متابعة',description:data.subject,sourceType:isContact?'contact':'followUp',sourceId:data.id,createdAt:now});}

export async function showCommunicationForm(kind,existing=null,afterSave=null){const rs=await refs();const title=kind==='contact'?(existing?'تعديل اتصال':'إضافة اتصال'):(existing?'تعديل متابعة':'إضافة متابعة');const {wrap,close}=modal(title,await followUpForm(existing||{},kind,rs));wrap.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);wrap.querySelector('#communicationForm').addEventListener('submit',async e=>{e.preventDefault();try{await saveCommunication(existing||{},new FormData(e.currentTarget),kind);close();toast('تم الحفظ بنجاح.');afterSave?.();}catch(err){toast(err.message,'error')}});}

async function announcementFollowUps(id){return (await repo(STORES.announcementFollowUps).all({ limit: 500 })).filter(x=>Number(x.announcementId)===Number(id)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));}
async function showAnnouncementFollowUp(announcementId,afterSave){const {wrap,close}=modal('تسجيل متابعة إعلان',`<form id="annFollow"><div class="form-grid"><div class="field"><label>التاريخ *</label><input class="input" type="date" name="date" required></div><div class="field"><label>الطريقة</label><select class="select" name="method">${opts(METHODS,'phone')}</select></div><div class="field"><label>الشخص</label><input class="input" name="person"></div><div class="field full"><label>النتيجة</label><textarea class="textarea" name="result" rows="3"></textarea></div><div class="field full"><label>ملاحظات</label><textarea class="textarea" name="notes" rows="2"></textarea></div></div><div class="form-actions"><button class="primary-button">حفظ</button><button class="secondary-button" type="button" data-close>إلغاء</button></div></form>`);wrap.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);wrap.querySelector('#annFollow').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const now=nowISO();try{await repo(STORES.announcementFollowUps).add({announcementId,date:val(fd,'date'),method:val(fd,'method'),person:val(fd,'person'),result:val(fd,'result'),notes:val(fd,'notes'),createdAt:now});close();toast('تم تسجيل متابعة الإعلان.');afterSave?.();}catch(err){toast(err.message,'error')}});}

function toolbar(button,label,searchId){return `<div class="toolbar"><button class="primary-button" data-add>${label}</button><input class="input" id="${searchId}" placeholder="بحث…" aria-label="بحث"></div>`;}

export async function renderAnnouncementsPage(page){let rows=await active(STORES.announcements),rs=await refs();const render=async()=>{rows=await active(STORES.announcements);const term=(page.querySelector('#annSearch')?.value||'').toLowerCase();const filtered=rows.filter(x=>`${x.announcementNumber||''} ${x.result||''} ${x.address||''} ${x.bailiffName||''}`.toLowerCase().includes(term));page.innerHTML=`${toolbar(null,'＋ إضافة إعلان','annSearch')}<section class="card">${sectionHeader('الإعلانات والمحضرين','سجل تشغيلي مستقل للإعلان ومتابعته')}${filtered.length?`<div class="table-list">${filtered.map(x=>`<article class="data-card"><div><strong>${escapeHtml(labelOf(ANN_TYPES,x.type))}</strong><span class="badge">${escapeHtml(labelOf(ANN_STATUS,x.status))}</span><p class="muted">${escapeHtml(x.announcementNumber?`${x.announcementNumber}/${x.announcementYear||''}`:'بدون رقم')} — ${escapeHtml(x.result||'لم تسجل النتيجة')}</p><small>${escapeHtml(x.serviceDate||x.deliveredDate||x.draftDate||'—')}</small></div><div class="row-actions"><button class="secondary-button" data-edit="${x.id}">تعديل</button><button class="secondary-button" data-follow="${x.id}">متابعة</button></div></article>`).join('')}</div>`:emptyState('لا توجد إعلانات مسجلة.')}</section>`;page.querySelector('[data-add]').onclick=()=>showAnnouncementForm(null,render);page.querySelector('#annSearch').oninput=render;page.querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>{const x=await repo(STORES.announcements).get(Number(b.dataset.edit));if(x)showAnnouncementForm(x,render)});page.querySelectorAll('[data-follow]').forEach(b=>b.onclick=()=>showAnnouncementFollowUp(Number(b.dataset.follow),render));};await render();return()=>{};}

async function renderCommunicationList(page,kind){const isContact=kind==='contact',store=isContact?STORES.contacts:STORES.followUps;let rows=await active(store);const title=isContact?'الاتصالات':'المتابعات';const render=async()=>{rows=await active(store);const term=(page.querySelector('#commSearch')?.value||'').toLowerCase();const filtered=rows.filter(x=>`${x.subject||''} ${x.result||''} ${x.person||''}`.toLowerCase().includes(term));page.innerHTML=`${toolbar(null,isContact?'＋ إضافة اتصال':'＋ إضافة متابعة','commSearch')}<section class="card">${sectionHeader(title,isContact?'سجل الاتصالات مع الأطراف':'سجل المتابعات المرتبطة بالعملاء والقضايا')}${filtered.length?`<div class="table-list">${filtered.map(x=>`<article class="data-card"><div><strong>${escapeHtml(x.subject)}</strong><span class="badge">${escapeHtml(labelOf(METHODS,x.method))}</span><p class="muted">${escapeHtml(x.person||'')} — ${escapeHtml(x.result||'')}</p><small>${escapeHtml(x.date||'')}${x.nextDate?` — التالي: ${escapeHtml(x.nextDate)}`:''}${x.nextAction?` — التالي: ${escapeHtml(x.nextAction)}`:''}</small></div><div class="row-actions"><button class="secondary-button" data-edit="${x.id}">تعديل</button></div></article>`).join('')}</div>`:emptyState(`لا توجد ${title} مسجلة.`)}</section>`;page.querySelector('[data-add]').onclick=()=>showCommunicationForm(kind,null,render);page.querySelector('#commSearch').oninput=render;page.querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>{const x=await repo(store).get(Number(b.dataset.edit));if(x)showCommunicationForm(kind,x,render)});};await render();return()=>{};}

export const renderFollowUpsPage=page=>renderCommunicationList(page,'follow-up');
export const renderContactsPage=page=>renderCommunicationList(page,'contact');

export async function renderAnnouncementDetails(page,id){const a=await repo(STORES.announcements).get(id);if(!a){page.innerHTML=emptyState('الإعلان غير موجود.');return()=>{};}const [rs,fu]=await Promise.all([refs(),announcementFollowUps(id)]);page.innerHTML=`<section class="card">${sectionHeader('تفاصيل الإعلان',`${labelOf(ANN_TYPES,a.type)} — ${labelOf(ANN_STATUS,a.status)}`)}<div class="detail-grid"><div><b>القضية</b><p>${escapeHtml(rs.cases.find(x=>x.id===a.caseId)?caseLabel(rs.cases.find(x=>x.id===a.caseId)):'—')}</p></div><div><b>العنوان</b><p>${escapeHtml(a.address||'—')}</p></div><div><b>المحضر</b><p>${escapeHtml(a.bailiffName||'—')}</p></div><div><b>تاريخ الإعلان</b><p>${escapeHtml(formatDate(a.serviceDate||a.deliveredDate||a.draftDate))}</p></div></div><hr><button class="primary-button" id="addAF">＋ تسجيل متابعة</button>${fu.length?`<div class="work-list">${fu.map(x=>`<div class="work-item"><div><span class="badge">${escapeHtml(labelOf(METHODS,x.method))}</span><strong>${escapeHtml(x.result||'متابعة')}</strong><p>${escapeHtml(x.person||'')}</p></div><time>${escapeHtml(x.date)}</time></div>`).join('')}</div>`:emptyState('لا توجد متابعات للإعلان.')}</section>`;page.querySelector('#addAF').onclick=()=>showAnnouncementFollowUp(id,()=>renderAnnouncementDetails(page,id));return()=>{};}
