import {repo} from './db/repositories.js';
import {STORES} from './core/constants.js';
import {escapeHtml, normalizeText, isActive} from './core/utils.js';;
import {toast} from './ui/toast.js';
import {getCriminalLawNotice,listCriminalLawVersions} from './criminal/criminal-engine.js';
const now=()=>new Date().toISOString();
const caseLabel=c=>c?`${c.caseNumber||'—'}/${c.caseYear||'—'} — ${c.subject||''}`:'—';
async function cases(){return(await repo(STORES.cases).all({ limit: 500 })).filter(x=>!x.archived)}
async function clients(){return(await repo(STORES.clients).all({ limit: 500 })).filter(x=>!x.archived)}
async function prosecutionOffices(){return(await repo(STORES.courtsAuthorities).all({ limit: 500 })).filter(x=>isActive(x)&&(x.type==='prosecution'||x.type==='police'||x.type==='other'))}
function modal(title,body){const w=document.createElement('div');w.className='modal-backdrop';w.innerHTML=`<div class="modal-card" role="dialog" aria-modal="true"><div class="modal-header"><h2>${escapeHtml(title)}</h2><button class="icon-button" data-close>×</button></div><div class="modal-body">${body}</div></div>`;document.body.appendChild(w);const close=()=>w.remove();w.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',close));return{wrap:w,close}}
function opts(arr,val,label){return `<option value="">— ${label} —</option>${arr.map(x=>`<option value="${x.id}" ${String(val??'')===String(x.id)?'selected':''}>${escapeHtml(x.label)}</option>`).join('')}`}
function form(existing,cs,cl,po){const v=k=>escapeHtml(existing?.[k]??'');return `<form id="criminalForm" class="form-grid">
<label>القضية*<select name="caseId" required>${opts(cs.map(c=>({id:c.id,label:caseLabel(c)})),existing?.caseId,'اختر القضية')}</select></label>
<label>العميل/المتهم المرتبط<select name="clientId">${opts(cl.map(c=>({id:c.id,label:c.fullName})),existing?.clientId,'اختر العميل')}</select></label>
<label>جهة التحقيق/النيابة<select name="prosecutionOfficeId">${opts(po.map(a=>({id:a.id,label:`${a.name} — ${a.type||''}`})),existing?.prosecutionOfficeId,'اختر الجهة')}</select></label>
<label>رقم المحضر<input name="policeReportNumber" value="${v('policeReportNumber')}"></label><label>سنة المحضر<input name="policeReportYear" inputmode="numeric" value="${v('policeReportYear')}"></label>
<label>رقم التحقيق<input name="investigationNumber" value="${v('investigationNumber')}"></label><label>سنة التحقيق<input name="investigationYear" inputmode="numeric" value="${v('investigationYear')}"></label>
<label>تاريخ الواقعة<input type="date" name="incidentDate" value="${v('incidentDate')}"></label><label>تاريخ القبض<input type="date" name="arrestDate" value="${v('arrestDate')}"></label>
<label>تاريخ الإفراج<input type="date" name="releaseDate" value="${v('releaseDate')}"></label>
<label>حالة الاحتجاز<select name="detentionStatus"><option value="غير محتجز">غير محتجز</option><option value="متحفظ عليه">متحفظ عليه</option><option value="محبوس احتياطياً">محبوس احتياطياً</option><option value="مفرج عنه">مفرج عنه</option><option value="أخرى">أخرى</option></select></label>
<label>بداية الاحتجاز<input type="date" name="detentionStartDate" value="${v('detentionStartDate')}"></label><label>نهاية الاحتجاز المسجلة<input type="date" name="detentionEndDate" value="${v('detentionEndDate')}"></label>
<label>تاريخ الإحالة<input type="date" name="referralDate" value="${v('referralDate')}"></label><label>جهة الإحالة<input name="referralAuthority" value="${v('referralAuthority')}"></label>
<label>درجة المحاكمة<input name="trialDegree" placeholder="جنح / جنايات أول درجة / استئناف..." value="${v('trialDegree')}"></label>
<label>التكييف/وصف الاتهام<input name="accusation" value="${v('accusation')}"></label>
<label class="full">وصف الاتهام التفصيلي<textarea name="chargeDescription" rows="3">${v('chargeDescription')}</textarea></label>
<label class="full">الحالة والتطورات<input name="statusDetails" value="${v('statusDetails')}"></label>
<label class="full">ملاحظات قانونية وتشغيلية<textarea name="notes" rows="4">${v('notes')}</textarea></label>
<div class="form-actions"><button type="button" class="secondary-button" data-close>إلغاء</button><button class="primary-button">حفظ</button></div></form>`}
export async function showCriminalForm(existing=null,onSaved=()=>{}){const[cs,cl,po]=await Promise.all([cases(),clients(),prosecutionOffices()]);const m=modal(existing?'تعديل الملف الجنائي':'إضافة ملف جنائي',form(existing,cs,cl,po));m.wrap.querySelector('#criminalForm').addEventListener('submit',async e=>{e.preventDefault();try{const f=Object.fromEntries(new FormData(e.currentTarget)),stamp=now();const data={caseId:Number(f.caseId),clientId:f.clientId?Number(f.clientId):null,prosecutionOfficeId:f.prosecutionOfficeId?Number(f.prosecutionOfficeId):null,policeReportNumber:f.policeReportNumber||'',policeReportYear:f.policeReportYear||'',investigationNumber:f.investigationNumber||'',investigationYear:f.investigationYear||'',incidentDate:f.incidentDate||'',arrestDate:f.arrestDate||'',releaseDate:f.releaseDate||'',detentionStatus:f.detentionStatus||'غير محتجز',detentionStartDate:f.detentionStartDate||'',detentionEndDate:f.detentionEndDate||'',referralDate:f.referralDate||'',referralAuthority:f.referralAuthority||'',trialDegree:f.trialDegree||'',accusation:f.accusation||'',chargeDescription:f.chargeDescription||'',statusDetails:f.statusDetails||'',notes:f.notes||'',updatedAt:stamp};if(existing)await repo(STORES.criminalDetails).put({...existing,...data,id:existing.id,createdAt:existing.createdAt||stamp});else await repo(STORES.criminalDetails).add({...data,createdAt:stamp});toast('تم حفظ الملف الجنائي.');m.close();await onSaved()}catch(err){toast(err.message,'error')}})}
function procedureForm(existing,rows){const v=k=>escapeHtml(existing?.[k]??'');return `<form id="criminalProcedureForm" class="form-grid"><label>الملف الجنائي*<select name="criminalDetailsId" required>${rows.map(r=>`<option value="${r.id}" ${String(existing?.criminalDetailsId||'')===String(r.id)?'selected':''}>${escapeHtml(r.label)}</option>`).join('')}</select></label><label>تاريخ الإجراء<input type="date" name="date" required value="${v('date')}"></label><label>نوع الإجراء<select name="type"><option>تحقيق</option><option>استجواب</option><option>مواجهة</option><option>تجديد حبس</option><option>إخلاء سبيل</option><option>إحالة</option><option>جلسة</option><option>طلب</option><option>أخرى</option></select></label><label>الجلسة المرتبطة<input name="relatedHearingId" inputmode="numeric" value="${v('relatedHearingId')}"></label><label class="full">وصف الإجراء<textarea name="description" rows="3">${v('description')}</textarea></label><label class="full">النتيجة<textarea name="result" rows="2">${v('result')}</textarea></label><label class="full">الإجراء التالي<textarea name="nextAction" rows="2">${v('nextAction')}</textarea></label><label class="full">ملاحظات<textarea name="notes" rows="2">${v('notes')}</textarea></label><div class="form-actions"><button type="button" class="secondary-button" data-close>إلغاء</button><button class="primary-button">حفظ الإجراء</button></div></form>`}
async function showProcedureForm(existing,rows,onSaved){const m=modal(existing?'تعديل الإجراء الجنائي':'إضافة إجراء جنائي',procedureForm(existing,rows));m.wrap.querySelector('#criminalProcedureForm').addEventListener('submit',async e=>{e.preventDefault();try{const f=Object.fromEntries(new FormData(e.currentTarget)),stamp=now(),data={criminalDetailsId:Number(f.criminalDetailsId),caseId:rows.find(x=>String(x.id)===String(f.criminalDetailsId))?.caseId||null,date:f.date,type:f.type||'',description:f.description||'',result:f.result||'',nextAction:f.nextAction||'',relatedHearingId:f.relatedHearingId?Number(f.relatedHearingId):null,notes:f.notes||'',updatedAt:stamp};if(existing)await repo(STORES.criminalProcedures).put({...existing,...data,id:existing.id,createdAt:existing.createdAt||stamp});else await repo(STORES.criminalProcedures).add({...data,createdAt:stamp});toast('تم حفظ الإجراء الجنائي.');m.close();await onSaved()}catch(err){toast(err.message,'error')}})}
export async function renderCriminalPage(page){const[rows,cs,cl,po,procedures]=await Promise.all([repo(STORES.criminalDetails).all({ limit: 500 }),cases(),clients(),prosecutionOffices(),repo(STORES.criminalProcedures).all({ limit: 500 })]);const cm=new Map(cs.map(x=>[Number(x.id),x])),lm=new Map(cl.map(x=>[Number(x.id),x])),pm=new Map(po.map(x=>[Number(x.id),x]));const notice=getCriminalLawNotice();const lawVersions=listCriminalLawVersions();const labels=rows.map(r=>({id:r.id,caseId:r.caseId,label:`${caseLabel(cm.get(Number(r.caseId)))} — ${r.investigationNumber||'بدون رقم تحقيق'}`}));page.innerHTML=`<section class="card"><div class="section-title"><div><h2>⚖️ مركز القضايا الجنائية</h2><p class="muted">إدارة الملف الجنائي والإجراءات والاحتجاز والإحالة مع فصل الوقائع المسجلة عن التكييف والاستنتاج القانوني.</p></div><button id="addCriminal" class="primary-button">＋ إضافة ملف جنائي</button></div><div class="notice warning">${escapeHtml(notice.text)} لا يقوم هذا المركز بإثبات مشروعية القبض أو الحبس، ولا يقرر بطلان إجراء أو انقضاء الدعوى أو صحة التكييف.</div><div class="toolbar"><input id="q" class="input" placeholder="بحث برقم المحضر أو التحقيق أو الاتهام أو القضية"><select id="statusFilter" class="input"><option value="">كل الحالات</option><option value="محبوس احتياطياً">محبوس احتياطياً</option><option value="متحفظ عليه">متحفظ عليه</option><option value="مفرج عنه">مفرج عنه</option><option value="غير محتجز">غير محتجز</option></select></div><div id="criminalList" class="work-list"></div></section><section class="grid grid-2"><section class="card"><div class="section-title"><div><h3>📜 الإجراءات الجنائية</h3><p class="muted">سجل تشغيلي للإجراءات المسجلة بالمكتب.</p></div><button id="addProcedure" class="secondary-button">＋ إضافة إجراء</button></div><div id="procedureList" class="work-list"></div></section><section class="card"><h3>📚 النظام الزمني لقانون الإجراءات الجنائية</h3>${lawVersions.map(r=>`<div class="work-item"><div><strong>${escapeHtml(r.name)}</strong><p class="muted">${escapeHtml(r.law)}</p><small>من ${escapeHtml(r.effectiveFrom)}${r.effectiveTo?` إلى ${escapeHtml(r.effectiveTo)}`:' وما بعده'} — ${escapeHtml(r.sourceReference)}</small></div></div>`).join('')}<div class="notice">المصدر الرسمي لقانون 174 لسنة 2025: الجريدة الرسمية، العدد 45 مكرر (د)، 12 نوفمبر 2025.</div></section></section>`;
const draw=()=>{const q=normalizeText(page.querySelector('#q').value),f=page.querySelector('#statusFilter').value;const list=rows.filter(r=>{const c=cm.get(Number(r.caseId)),text=normalizeText(`${r.policeReportNumber||''} ${r.investigationNumber||''} ${r.accusation||''} ${r.chargeDescription||''} ${caseLabel(c)} ${r.statusDetails||''}`);return(!q||text.includes(q))&&(!f||r.detentionStatus===f)});page.querySelector('#criminalList').innerHTML=list.length?list.map(r=>`<div class="work-item"><div><strong>${escapeHtml(caseLabel(cm.get(Number(r.caseId))))}</strong><span class="badge">${escapeHtml(r.detentionStatus||'—')}</span><p class="muted">اتهام: ${escapeHtml(r.accusation||'—')}</p><small>محضر: ${escapeHtml(r.policeReportNumber||'—')}/${escapeHtml(r.policeReportYear||'—')} — تحقيق: ${escapeHtml(r.investigationNumber||'—')}/${escapeHtml(r.investigationYear||'—')} — ${escapeHtml(pm.get(Number(r.prosecutionOfficeId))?.name||'جهة غير محددة')}</small><br><small>العميل المرتبط: ${escapeHtml(lm.get(Number(r.clientId))?.fullName||'—')} — الإحالة: ${escapeHtml(r.referralDate||'—')}</small></div><div class="row-actions"><button class="secondary-button" data-edit="${r.id}">تعديل</button></div></div>`).join(''):'<p class="muted">لا توجد ملفات جنائية مسجلة.</p>';page.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>showCriminalForm(rows.find(x=>Number(x.id)===Number(b.dataset.edit)),draw)))};
const drawProcedures=()=>{const map=new Map(rows.map(r=>[Number(r.id),r]));const list=procedures.slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));page.querySelector('#procedureList').innerHTML=list.length?list.map(r=>`<div class="work-item"><div><strong>${escapeHtml(r.type||'إجراء')}</strong><p class="muted">${escapeHtml(r.date||'—')} — ${escapeHtml(caseLabel(cm.get(Number(r.caseId))))}</p><small>${escapeHtml(r.description||'')} ${r.result?` — النتيجة: ${escapeHtml(r.result)}`:''}</small></div><div class="row-actions"><button class="secondary-button" data-pedit="${r.id}">تعديل</button></div></div>`).join(''):'<p class="muted">لا توجد إجراءات مسجلة.</p>';page.querySelectorAll('[data-pedit]').forEach(b=>b.addEventListener('click',()=>showProcedureForm(procedures.find(x=>Number(x.id)===Number(b.dataset.pedit)),labels,drawProcedures)))};
draw();drawProcedures();page.querySelector('#addCriminal').addEventListener('click',()=>showCriminalForm(null,draw));page.querySelector('#addProcedure').addEventListener('click',()=>rows.length?showProcedureForm(null,labels,drawProcedures):toast('أضف ملفًا جنائيًا أولًا.','error'));page.querySelector('#q').addEventListener('input',draw);page.querySelector('#statusFilter').addEventListener('change',draw);return()=>{}}
