import { repo } from './db/repositories.js';
import { STORES } from './core/constants.js';
import { parseMoneyMinor } from './core/money.js';
import {escapeHtml, normalizeText} from './core/utils.js';
import { toast } from './ui/toast.js';
import { calculateLaborDeadline, saveLaborCalculation, listLaborRules, calculateEntitlements, saveEntitlementCalculation } from './calculators/labor-engine.js';

const now=()=>new Date().toISOString();
const qid=()=>{const p=new URLSearchParams(location.hash.split('?')[1]||'');return p.get('id')};
const money=n=>Number(n||0).toLocaleString('ar-EG',{minimumFractionDigits:2,maximumFractionDigits:2});
const caseLabel=c=>c?`${c.caseNumber||'—'}/${c.caseYear||'—'} — ${c.subject||''}`:'—';

async function activeCases(){return (await repo(STORES.cases).all({ limit: 500 })).filter(x=>!x.archived);}
async function clients(){return (await repo(STORES.clients).all({ limit: 500 })).filter(x=>!x.archived);}

function formHtml(existing,cases,people){
  const opts=(arr,value,placeholder='— اختر —')=>`<option value="">${placeholder}</option>${arr.map(x=>`<option value="${x.id}" ${String(value||'')===String(x.id)?'selected':''}>${escapeHtml(x.label)}</option>`).join('')}`;
  const v=(k,d='')=>escapeHtml(existing?.[k]??d);
  return `<form id="laborForm" class="form-grid"><label>القضية*<select name="caseId" required>${opts(cases.map(c=>({id:c.id,label:caseLabel(c)})),existing?.caseId)}</select></label><label>العامل/العميل<select name="clientId">${opts(people.map(c=>({id:c.id,label:c.fullName})),existing?.clientId)}</select></label><label>نوع العلاقة<select name="employmentType"><option value="private">قطاع خاص</option><option value="other">أخرى</option></select></label><label>اسم صاحب العمل<input name="employerName" value="${v('employerName')}"></label><label>صفة صاحب العمل<input name="employerEntityType" value="${v('employerEntityType')}"></label><label>الوظيفة<input name="jobTitle" value="${v('jobTitle')}"></label><label>تاريخ بدء العمل<input type="date" name="startDate" value="${v('startDate')}"></label><label>تاريخ انتهاء العمل<input type="date" name="endDate" value="${v('endDate')}"></label><label>الأجر الشهري<input name="wage" inputmode="decimal" value="${v('wageMinor')?money(Number(existing.wageMinor)/100):''}"></label><label>دورية الأجر<input name="wagePeriod" value="${v('wagePeriod','monthly')}"></label><label>نوع العقد<input name="contractType" value="${v('contractType')}"></label><label>سبب/نوع الإنهاء<input name="terminationType" value="${v('terminationType')}"></label><label>تاريخ الإنهاء<input type="date" name="terminationDate" value="${v('terminationDate')}"></label><label>سبب الإنهاء<textarea name="terminationReason" rows="2">${v('terminationReason')}</textarea></label><label>مكان العمل<input name="workplace" value="${v('workplace')}"></label><label>حالة التأمينات<input name="insuranceStatus" value="${v('insuranceStatus')}"></label><label class="full">مكونات الأجر / البيانات الإضافية<textarea name="wageComponents" rows="3">${v('wageComponents')}</textarea></label><label class="full">ملاحظات<textarea name="notes" rows="4">${v('notes')}</textarea></label><div class="form-actions"><button type="button" class="secondary-button" data-close>إلغاء</button><button class="primary-button">حفظ</button></div></form>`;
}
function modal(title,body){
  const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<div class="modal-card" role="dialog" aria-modal="true"><div class="modal-header"><h2>${escapeHtml(title)}</h2><button class="icon-button" data-close>×</button></div><div class="modal-body">${body}</div></div>`;document.body.appendChild(wrap);const close=()=>wrap.remove();wrap.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',close));return {wrap,close};
}

export async function showLaborForm(existing=null,onSaved=()=>{}){
  const [cases,people]=await Promise.all([activeCases(),clients()]);
  const m=modal(existing?'تعديل ملف عمالي':'إضافة ملف عمالي',formHtml(existing,cases,people));
  m.wrap.querySelector('#laborForm').addEventListener('submit',async e=>{e.preventDefault();try{const fd=Object.fromEntries(new FormData(e.currentTarget));const wageMinor=parseMoneyMinor(fd.wage,{emptyValue:0});const stamp=now();const data={caseId:Number(fd.caseId),clientId:fd.clientId?Number(fd.clientId):null,employmentType:fd.employmentType||'',employerName:fd.employerName||'',employerEntityType:fd.employerEntityType||'',jobTitle:fd.jobTitle||'',startDate:fd.startDate||'',endDate:fd.endDate||'',wageMinor,wagePeriod:fd.wagePeriod||'',wageComponents:fd.wageComponents||'',terminationType:fd.terminationType||'',terminationDate:fd.terminationDate||'',terminationReason:fd.terminationReason||'',contractType:fd.contractType||'',workplace:fd.workplace||'',insuranceStatus:fd.insuranceStatus||'',notes:fd.notes||'',updatedAt:stamp};if(existing)await repo(STORES.laborDetails).put({...existing,...data,id:existing.id,createdAt:existing.createdAt||stamp});else data.createdAt=stamp,await repo(STORES.laborDetails).add(data);toast('تم حفظ الملف العمالي.');m.close();await onSaved();}catch(err){toast(err.message,'error')}});
}

export async function renderLaborPage(page){
  const refresh=()=>window.dispatchEvent(new Event('hashchange'));
  const [rows,cases,people]=await Promise.all([repo(STORES.laborDetails).all({ limit: 500 }),activeCases(),clients()]);
  const caseMap=new Map(cases.map(x=>[Number(x.id),x])), peopleMap=new Map(people.map(x=>[Number(x.id),x]));
  page.innerHTML=`<section class="card"><div class="section-title"><div><h2>👷 مركز القضايا العمالية</h2><p class="muted">إدارة بيانات العلاقة العمالية، المواعيد العمالية المحددة بالقانون، وحسابات المستحقات القابلة للمراجعة.</p></div><button id="addLabor" class="primary-button">＋ إضافة ملف عمالي</button></div><div class="notice warning">القواعد المفعلة في هذه المرحلة مبنية على قانون العمل رقم 14 لسنة 2025 كما تم التحقق منه في 24 سبتمبر 2026. الحساب لا يحسم الاستحقاق القانوني ولا صحة الوقائع.</div><div class="toolbar"><input id="q" class="input" placeholder="بحث بالعامل أو صاحب العمل أو القضية"><select id="filter" class="input"><option value="">كل الملفات</option><option value="active">بها علاقة عمل</option><option value="ended">منتهية</option></select></div><div id="laborList" class="work-list"></div></section><section id="laborTools" class="grid grid-2"></section>`;
  const draw=()=>{const q=normalizeText(page.querySelector('#q').value),filter=page.querySelector('#filter').value;const list=rows.filter(r=>{const c=caseMap.get(Number(r.caseId)),p=peopleMap.get(Number(r.clientId));const text=normalizeText(`${p?.fullName||''} ${r.employerName||''} ${caseLabel(c)} ${r.jobTitle||''}`);return(!q||text.includes(q))&&(!filter||(filter==='ended'?!!r.endDate:!r.endDate))});page.querySelector('#laborList').innerHTML=list.length?list.map(r=>`<div class="work-item"><div><strong>${escapeHtml(peopleMap.get(Number(r.clientId))?.fullName||r.employerName||'ملف عمالي')}</strong><span class="badge">${escapeHtml(r.contractType||'غير محدد')}</span><p class="muted">${escapeHtml(caseLabel(caseMap.get(Number(r.caseId))))} — ${escapeHtml(r.jobTitle||'')}</p><small>الأجر: ${r.wageMinor?money(Number(r.wageMinor)/100):'—'} — الإنهاء: ${escapeHtml(r.terminationDate||'—')}</small></div><div class="row-actions"><button class="secondary-button" data-edit="${r.id}">تعديل</button></div></div>`).join(''):'<p class="muted">لا توجد ملفات عمالية.</p>';page.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>showLaborForm(rows.find(x=>Number(x.id)===Number(b.dataset.edit)),refresh)))};
  page.querySelector('#addLabor').addEventListener('click',()=>showLaborForm(null,refresh));page.querySelector('#q').addEventListener('input',draw);page.querySelector('#filter').addEventListener('change',draw);draw();
  const rules=await listLaborRules();
  page.querySelector('#laborTools').innerHTML=`<section class="card"><h3>🕐 مواعيد عمالية</h3><p class="muted">أدخل نقطة البداية التي تحددت من الواقعة، ثم راجع النتيجة مع النص والملف.</p><form id="laborDeadline" class="form-grid"><label>القاعدة<select name="ruleId">${rules.map(r=>`<option value="${r.id}">${escapeHtml(r.name)} — ${r.duration} ${r.unit==='months'?'شهر':'يوم'}</option>`).join('')}</select></label><label>تاريخ البداية<input type="date" name="startDate" required></label><label>القضية<select name="caseId"><option value="">— بدون ربط —</option>${cases.map(c=>`<option value="${c.id}">${escapeHtml(caseLabel(c))}</option>`).join('')}</select></label><div class="form-actions"><button class="primary-button">احسب الميعاد</button></div></form><div id="laborDeadlineResult"></div></section><section class="card"><h3>💰 حساب مستحقات العامل</h3><p class="muted">حسابات منفصلة لكل بند، مع تحذيرات وشروط المادة.</p><form id="entitlementForm" class="form-grid"><label>الأجر الشهري<input name="monthlyWage" type="number" min="0" step="0.01" required></label><label>عدد أشهر مهلة الإخطار غير المنفذة<input name="noticeMonths" type="number" min="0" step="0.01" value="0"></label><label>أيام رصيد الإجازات المدخلة<input name="leaveDays" type="number" min="0" step="0.01" value="0"></label><label>سنوات الخدمة المحتسبة<input name="serviceYears" type="number" min="0" step="0.01" value="0"></label><label>هل الإنهاء غير المشروع متحقق قانوناً؟<select name="unlawfulTermination"><option value="no">لا / لم يثبت</option><option value="yes">نعم — بعد التحقق</option></select></label><label>هل المدة محل الحساب بعد سن الستين؟<select name="post60"><option value="no">لا</option><option value="yes">نعم — بعد التحقق</option></select></label><label>هل تنطبق حالة العقد الذي تجاوز خمس سنوات؟<select name="fixedTermOver5"><option value="no">لا</option><option value="yes">نعم — بعد التحقق</option></select></label><label>القضية<select name="caseId"><option value="">— بدون ربط —</option>${cases.map(c=>`<option value="${c.id}">${escapeHtml(caseLabel(c))}</option>`).join('')}</select></label><div class="form-actions"><button class="primary-button">احسب المستحقات</button></div></form><div id="entitlementResult"></div></section>`;
  page.querySelector('#laborDeadline').addEventListener('submit',async e=>{e.preventDefault();try{const fd=Object.fromEntries(new FormData(e.currentTarget));const r=await calculateLaborDeadline(fd);await saveLaborCalculation(r);page.querySelector('#laborDeadlineResult').innerHTML=`<div class="result-card"><h3>النتيجة الحسابية</h3><div class="result-date">${escapeHtml(r.deadline)}</div><p><strong>${escapeHtml(r.ruleName)}</strong> — ${escapeHtml(r.duration+' '+(r.unit==='months'?'شهر':'يوم'))}</p><ul>${r.warnings.map(w=>`<li>${escapeHtml(w)}</li>`).join('')}</ul><p class="muted">${escapeHtml(r.sourceReference)}</p></div>`;toast('تم حساب الميعاد وحفظه في سجل الحسابات.')}catch(err){toast(err.message,'error')}});
  page.querySelector('#entitlementForm').addEventListener('submit',async e=>{e.preventDefault();try{const fd=Object.fromEntries(new FormData(e.currentTarget));const r=calculateEntitlements(fd);const caseId=fd.caseId||null;await saveEntitlementCalculation(r,caseId);page.querySelector('#entitlementResult').innerHTML=`<div class="result-card"><h3>إجمالي حسابي مدخل</h3><div class="result-date">${money(r.total)} جنيه</div>${r.items.map(x=>`<div class="table-row"><strong>${escapeHtml(x.label)}</strong><span>${money(x.amount)} جنيه</span><small>${escapeHtml(x.formula)}</small></div>`).join('')}<ul>${r.warnings.map(w=>`<li>${escapeHtml(w)}</li>`).join('')}</ul></div>`;toast('تم حساب المستحقات وحفظها في سجل الحسابات.')}catch(err){toast(err.message,'error')}});
  return ()=>{};
}
