export const STORES = Object.freeze({
  clients: 'clients',
  opponents: 'opponents',
  powerOfAttorneys: 'powerOfAttorneys',
  cases: 'cases',
  caseClients: 'caseClients',
  caseOpponents: 'caseOpponents',
  casePowerOfAttorneys: 'casePowerOfAttorneys',
  hearings: 'hearings',
  procedures: 'procedures',
  judgments: 'judgments',
  appeals: 'appeals',
  caseRelations: 'caseRelations',
  caseEvents: 'caseEvents',
  caseTasks: 'caseTasks',
  announcements: 'announcements',
  announcementFollowUps: 'announcementFollowUps',
  executionFiles: 'executionFiles',
  executionProcedures: 'executionProcedures',
  collections: 'collections',
  settlements: 'settlements',
  settlementSessions: 'settlementSessions',
  experts: 'experts',
  expertSessions: 'expertSessions',
  followUps: 'followUps',
  contacts: 'contacts',
  courtsAuthorities: 'courtsAuthorities',
  financialRecords: 'financialRecords',
  feeAgreements: 'feeAgreements',
  laborDetails: 'laborDetails',
  administrativeDetails: 'administrativeDetails',
  administrativeGrievances: 'administrativeGrievances',
  administrativeProcedures: 'administrativeProcedures',
  criminalDetails: 'criminalDetails',
  criminalProcedures: 'criminalProcedures',
  familyDetails: 'familyDetails',
  familyMaintenancePeriods: 'familyMaintenancePeriods',
  familyPayments: 'familyPayments',
  lookups: 'lookups',
  settings: 'settings',
  backupHistory: 'backupHistory',
  legalRules: 'legalRules',
  holidays: 'holidays',
  calculationHistory: 'calculationHistory',
  teamMembers: 'teamMembers',
  teamRoles: 'teamRoles',
  templates: 'templates',
  auditLog: 'auditLog'
});

export const NAV_GROUPS = Object.freeze([
  { title: 'التشغيل اليومي', items: [['dashboard', '🏠', 'الرئيسية'], ['daily', '🎯', 'يومي'], ['quick-add', '⚡', 'إضافة سريعة'], ['search', '🔎', 'البحث الشامل']] },
  { title: 'الأشخاص', items: [['clients', '👤', 'العملاء'], ['opponents', '👥', 'الخصوم'], ['power-of-attorneys', '📄', 'التوكيلات'], ['team', '👨‍⚖️', 'فريق المكتب']] },
  { title: 'الملفات القضائية', items: [['cases', '⚖️', 'القضايا'], ['hearings', '📅', 'الجلسات'], ['judgments', '📝', 'الأحكام'], ['appeals', '📑', 'الطعون'], ['execution', '🏛️', 'التنفيذ']] },
  { title: 'الإجراءات والمتابعة', items: [['tasks', '📋', 'المهام'], ['announcements', '📜', 'الإعلانات والمحضرين'], ['follow-ups', '📞', 'المتابعات والاتصالات'], ['experts', '📐', 'الخبراء'], ['settlements', '📑', 'التسويات']] },
  { title: 'الجهات', items: [['courts', '🏛️', 'المحاكم والجهات']] },
  { title: 'الأدوات القانونية', items: [['financial', '💰', 'المركز المالي'], ['calculators', '🧮', 'الحاسبات القانونية'], ['labor', '👷', 'مركز القضايا العمالية'], ['family', '👨‍👩‍👧‍👦', 'مركز النفقات الأسرية'], ['administrative', '🏛️', 'المنازعات الإدارية'], ['criminal', '⚖️', 'مركز القضايا الجنائية']] },
  { title: 'المعلومات', items: [['reports', '📑', 'التقارير'], ['statistics', '📊', 'الإحصائيات والتحليلات'], ['data-quality', '🛡️', 'صحة البيانات'], ['performance', '⚡', 'أداء النظام'], ['audit', '🧾', 'سجل العمليات'], ['archive', '🗃️', 'الأرشيف']] },
  { title: 'النظام', items: [['sync', '🔄', 'المزامنة'], ['templates', '🧩', 'القوالب'], ['backup', '💾', 'النسخ الاحتياطي والاستعادة'], ['settings', '⚙️', 'الإعدادات']] }
]);
