import { repo, transaction } from '../db/repositories.js';
import { STORES } from '../core/constants.js';
import { normalizeText, escapeHtml, nowISO, debounce } from '../core/utils.js';
import { validateCase } from '../core/validators.js';
import { toast } from '../ui/toast.js';
import { emptyState } from '../ui/components.js';
import { formatDate } from '../core/dates.js';
import { clampPageSize, resetPage } from '../core/performance.js';
import { asyncSelectHtml, mountAsyncSelect } from '../ui/async-select.js';
import { buildCaseGraph, renderCaseGraph } from './case-graph.js';
import { getCaseTimeline } from '../timeline/timeline.js';

const activeRows = async store => (await repo(store).all({ limit: 500 })).filter(row => !row.archived);
const allRows = async store => repo(store).all({ limit: 500 });
const value = (fd, name) => String(fd.get(name) ?? '').trim();
const queryParams = () => new URLSearchParams((location.hash.split('?')[1] || '').split('#')[0]);
const queryId = () => Number(queryParams().get('id')) || null;
const queryView = () => queryParams().get('view') || 'list';

const CASE_TYPES = [['civil','مدني'],['rental','إيجارات'],['family','أسرة'],['criminal','جنائي'],['labor','عمالي'],['administrative','إداري'],['commercial','تجاري'],['real-estate','عقاري'],['signature-validity','صحة توقيع'],['other','أخرى']];
const DEGREES = [['first','أول درجة'],['appeal','استئناف'],['cassation','نقض'],['other','أخرى']];
const STATUSES = [['open','منظورة'],['pending','معلقة'],['closed','منتهية'],['archived','مؤرشفة'],['other','أخرى']];
const CLIENT_ROLES = [['plaintiff','مدعٍ'],['defendant','مدعى عليه'],['appellant','مستأنف'],['respondent','مستأنف ضده'],['claimant','طالب'],['respondent-other','معلن إليه/طرف'],['other','أخرى']];
const RELATIONS = [['original','أصلية'],['appeal','استئناف'],['cassation','نقض'],['related','مرتبطة'],['counterclaim','دعوى فرعية/مقابلة'],['intervention','تدخل'],['grievance','تظلم'],['other','أخرى']];
const labelOf = (items, value) => items.find(x => x[0] === value)?.[1] || value || '—';
const options = (items, selected = '') => items.map(([v,l]) => `<option value="${escapeHtml(v)}" ${String(v)===String(selected)?'selected':''}>${escapeHtml(l)}</option>`).join('');

function modalFrame(title, content) {
  const wrap=document.createElement('div'); wrap.className='modal-backdrop';
  wrap.innerHTML=`<section class="modal people-modal case-modal" role="dialog" aria-modal="true" aria-labelledby="caseModalTitle"><div class="modal-header"><h2 id="caseModalTitle">${escapeHtml(title)}</h2><button class="icon-button" type="button" data-close aria-label="إغلاق">×</button></div>${content}</section>`;
  const close=()=>wrap.remove(); wrap.querySelector('[data-close]').addEventListener('click',close); wrap.addEventListener('click',e=>{if(e.target===wrap)close();}); document.getElementById('modalRoot').appendChild(wrap); return {wrap,close};
}

function caseFormHtml({row={}}={}) {
  const clientLabel = row.clientId ? String(row.clientName || '') : '';
  const courtLabel = row.courtId ? String(row.courtName || '') : '';
  return `<form id="caseForm"><div class="form-grid">
  <div class="field"><label for="caseNumber">رقم القضية *</label><input id="caseNumber" name="caseNumber" class="input" required value="${escapeHtml(row.caseNumber)}"></div>
  <div class="field"><label for="caseYear">السنة *</label><input id="caseYear" name="caseYear" class="input" type="number" min="1900" max="2200" required value="${escapeHtml(row.caseYear)}"></div>
  <div class="field"><label for="caseType">نوع القضية *</label><select id="caseType" name="caseType" class="select" required><option value="">اختر النوع</option>${options(CASE_TYPES,row.caseType)}</select></div>
  <div class="field"><label for="caseSubtype">التصنيف الفرعي</label><input id="caseSubtype" name="caseSubtype" class="input" value="${escapeHtml(row.caseSubtype)}" placeholder="فسخ، طرد، مطالبة…"></div>
  <div class="field"><label for="caseDegree">الدرجة</label><select id="caseDegree" name="degree" class="select"><option value="">غير محددة</option>${options(DEGREES,row.degree)}</select></div>
  <div class="field"><label for="caseStatus">الحالة</label><select id="caseStatus" name="status" class="select">${options(STATUSES,row.status||'open')}</select></div>
  <div class="field">${asyncSelectHtml({id:'caseCourt',name:'courtId',label:'المحكمة/الجهة',placeholder:'اكتب اسم المحكمة أو الجهة…',value:row.courtId||'',displayValue:courtLabel})}</div>
  <div class="field"><label for="caseChamber">الدائرة</label><input id="caseChamber" name="chamber" class="input" value="${escapeHtml(row.chamber)}"></div>
  <div class="field"><label for="caseFilingDate">تاريخ القيد/الرفع</label><input id="caseFilingDate" name="filingDate" class="input" type="date" value="${escapeHtml(row.filingDate)}"></div>
  <div class="field"><label for="caseValue">قيمة القضية — كما سجلها المستخدم</label><input id="caseValue" name="caseValue" class="input" value="${escapeHtml(row.caseValue)}"></div>
  <div class="field">${asyncSelectHtml({id:'caseClient',name:'clientId',label:'العميل الأساسي',placeholder:'اكتب اسم العميل…',value:row.clientId||'',displayValue:clientLabel})}</div>
  <div class="field"><label for="caseClientRole">صفة العميل</label><select id="caseClientRole" name="clientRole" class="select"><option value="">غير محددة</option>${options(CLIENT_ROLES,row.clientRole)}</select></div>
  <div class="field full"><label for="caseSubject">موضوع القضية</label><textarea id="caseSubject" name="subject" class="textarea" rows="3">${escapeHtml(row.subject)}</textarea></div>
  <div class="field full"><label for="caseSource">مصدر الملف/الإحالة</label><input id="caseSource" name="source" class="input" value="${escapeHtml(row.source)}"></div>
  <div class="field full"><label for="caseNotes">ملاحظات</label><textarea id="caseNotes" name="notes" class="textarea" rows="3">${escapeHtml(row.notes)}</textarea></div></div>
  <p class="muted form-note">البحث عن العميل والمحكمة/الجهة يتم عند الكتابة ولا يحمل قوائم كاملة إلى الذاكرة. هذه بيانات إدارية مسجلة بواسطة المستخدم؛ لا يستنتج النظام منها نهائية الحكم أو مواعيد الطعن أو أي أثر قانوني تلقائي.</p>
  <div class="form-actions"><button class="primary-button" type="submit">حفظ القضية</button><button class="secondary-button" type="button" data-close>إلغاء</button></div></form>`;
}

function displayNumber(row){return `${row.caseNumber||'—'} / ${row.caseYear||'—'}`;}
function courtName(courts,id){return courts.find(c=>Number(c.id)===Number(id))?.name||'—';}
function clientName(clients,id){return clients.find(c=>Number(c.id)===Number(id))?.fullName||'—';}
function opponentName(opponents,id){return opponents.find(c=>Number(c.id)===Number(id))?.name||'—';}

async function saveCase(form, existing=null) {
  const fd=new FormData(form); const row={...(existing||{}),caseNumber:value(fd,'caseNumber'),caseYear:Number(value(fd,'caseYear')),caseType:value(fd,'caseType'),caseSubtype:value(fd,'caseSubtype'),courtId:value(fd,'courtId')?Number(value(fd,'courtId')):'',chamber:value(fd,'chamber'),degree:value(fd,'degree'),filingDate:value(fd,'filingDate'),status:value(fd,'status')||'open',subject:value(fd,'subject'),caseValue:value(fd,'caseValue'),clientRole:value(fd,'clientRole'),source:value(fd,'source'),notes:value(fd,'notes'),archived:existing?.archived??false,createdAt:existing?.createdAt||nowISO(),updatedAt:nowISO()};
  validateCase(row);
  const duplicates=(await activeRows(STORES.cases)).filter(x=>Number(x.id)!==Number(row.id));
  const duplicate=duplicates.find(x=>normalizeText(x.caseNumber)===normalizeText(row.caseNumber)&&Number(x.caseYear)===Number(row.caseYear)&&Number(x.courtId||0)===Number(row.courtId||0));
  if(duplicate&&!window.confirm(`توجد قضية بنفس الرقم والسنة ونفس المحكمة/الجهة (معرف ${duplicate.id}). هل تريد الحفظ رغم احتمال التكرار؟`))throw new Error('تم إلغاء الحفظ بسبب احتمال التكرار.');
  const clientId=value(fd,'clientId')?Number(value(fd,'clientId')):null;
  if(clientId){const client=await repo(STORES.clients).get(clientId);if(!client||client.archived)throw new Error('العميل المختار غير موجود أو مؤرشف.');}
  if(row.courtId){const court=await repo(STORES.courtsAuthorities).get(row.courtId);if(!court||court.active===false)throw new Error('المحكمة/الجهة المختارة غير متاحة.');}
  let caseId=null;
  await transaction([STORES.cases,STORES.caseClients,STORES.caseEvents],'readwrite',tx=>{
    const casesStore=tx.objectStore(STORES.cases), relStore=tx.objectStore(STORES.caseClients), eventStore=tx.objectStore(STORES.caseEvents);
    const request=existing?.id?casesStore.put({...row,id:existing.id}):casesStore.add(row);
    request.onsuccess=()=>{caseId=Number(request.result); if(clientId){const get=relStore.index('caseId').openCursor(caseId);let found=false;get.onsuccess=()=>{const cursor=get.result;if(!cursor){if(!found)relStore.add({caseId,clientId,role:row.clientRole||'other',isPrimary:true,notes:'',createdAt:nowISO()});return;}if(Number(cursor.value.clientId)===clientId){found=true;return;}cursor.continue();};} eventStore.add({caseId,eventType:existing?'case-updated':'case-created',eventDate:row.filingDate||new Date().toISOString().slice(0,10),title:existing?'تعديل بيانات القضية':'إنشاء القضية',description:`تم ${existing?'تعديل':'إنشاء'} السجل الإداري للقضية ${displayNumber(row)}.`,sourceType:'cases',sourceId:caseId,createdAt:nowISO()});};
  });
  return caseId;
}

export function showCaseForm(existing=null,afterSave=null){(async()=>{try{const [client,court]=await Promise.all([existing?.clientId?repo(STORES.clients).get(Number(existing.clientId)):null,existing?.courtId?repo(STORES.courtsAuthorities).get(Number(existing.courtId)):null]);const row={...(existing||{}),clientName:client?.fullName||'',courtName:court?.name||''};const {wrap,close}=modalFrame(existing?'تعديل القضية':'إضافة قضية',caseFormHtml({row}));wrap.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',close));mountAsyncSelect(wrap.querySelector('[data-name="clientId"]'),{store:STORES.clients,index:'normalizedName',labelField:'fullName',initialValue:row.clientId||'',initialLabel:row.clientName||'',filter:r=>!r.archived});mountAsyncSelect(wrap.querySelector('[data-name="courtId"]'),{store:STORES.courtsAuthorities,index:'name',labelField:'name',secondaryField:'city',initialValue:row.courtId||'',initialLabel:row.courtName||'',filter:r=>r.active!==false});wrap.querySelector('#caseForm').addEventListener('submit',async e=>{e.preventDefault();try{const id=await saveCase(e.currentTarget,existing);close();toast(existing?'تم تعديل القضية.':'تم إنشاء القضية.');afterSave?.(id);}catch(err){toast(err.message||'تعذر حفظ القضية.','error');}});}catch(err){toast(err.message||'تعذر فتح نموذج القضية.','error');}})();}

async function archiveCase(id,after=null){const row=await repo(STORES.cases).get(Number(id));if(!row)return;if(!window.confirm(`هل تريد أرشفة القضية ${displayNumber(row)}؟ لن يتم حذف العلاقات أو الأحداث.`))return;row.archived=true;row.updatedAt=nowISO();await repo(STORES.cases).put(row);toast('تمت أرشفة القضية.');after?.();}

async function renderCaseList(page){
  const caseRepo=repo(STORES.cases), [activeCount,courts]=await Promise.all([caseRepo.countByIndex('archived',false), repo(STORES.courtsAuthorities).page({index:'active',query:true,direction:'next',limit:500})]);
  const courtRows=courts.rows||[]; const courtMap=new Map(courtRows.map(c=>[Number(c.id),c.name]));
  const state={pageSize:clampPageSize(50),afterKey:undefined,afterPrimaryKey:undefined,hasMore:true,pageNumber:1}; const history=[]; let currentRows=[];
  page.innerHTML=`<section class="card people-page cases-page"><div class="section-title"><div><h2>القضايا</h2><p class="muted">تحميل القضايا على دفعات من IndexedDB؛ لا يتم تحميل مئات الآلاف من السجلات إلى الذاكرة.</p></div><button id="addCase" class="primary-button">＋ إضافة قضية</button></div><div class="toolbar cases-toolbar"><input id="caseSearch" class="input toolbar-search" placeholder="بحث برقم القضية أو الموضوع…" aria-label="بحث القضايا"><select id="caseTypeFilter" class="select"><option value="">كل الأنواع</option>${options(CASE_TYPES)}</select><select id="caseStatusFilter" class="select"><option value="">كل الحالات</option>${options(STATUSES)}</select><span class="badge">${activeCount} قضية نشطة</span></div><div id="caseList" class="list"></div><div class="pager"><button id="prevCases" class="secondary-button" disabled>السابق</button><span id="casePageInfo" class="muted">الصفحة 1</span><button id="nextCases" class="secondary-button">التالي</button></div></section>`;
  const list=page.querySelector('#caseList'),search=page.querySelector('#caseSearch'),typeFilter=page.querySelector('#caseTypeFilter'),statusFilter=page.querySelector('#caseStatusFilter');
  const draw=async(reset=false)=>{
    if(reset){resetPage(state);history.length=0;currentRows=[];}
    const q=normalizeText(search.value),type=typeFilter.value,status=statusFilter.value;
    if(!q&&!type&&!status){
      const result=await caseRepo.pageByIndex('archived',false,{direction:'next',limit:state.pageSize,afterKey:state.afterKey,afterPrimaryKey:state.afterPrimaryKey});
      currentRows=result.rows;state.afterKey=result.nextKey;state.afterPrimaryKey=result.nextPrimaryKey;state.hasMore=result.hasMore;
    }else{
      const candidates=new Map();
      if(q){
        try{const byNum=await caseRepo.prefix('caseNumber',q,{limit:300});for(const row of byNum.rows)if(!row.archived)candidates.set(row.id,row);}catch{}
        await caseRepo.scan({index:'archived',query:false,direction:'next',limit:1200,onRow:row=>{if(!row.archived&&[row.caseNumber,row.caseYear,row.caseSubtype,row.subject].some(v=>normalizeText(v).includes(q)))candidates.set(row.id,row);}});
      }else{
        await caseRepo.scan({index:'archived',query:false,direction:'next',limit:1200,onRow:row=>candidates.set(row.id,row)});
      }
      currentRows=[...candidates.values()].filter(c=>(!type||c.caseType===type)&&(!status||c.status===status)).slice(0,state.pageSize);state.hasMore=false;
    }
    list.innerHTML=currentRows.length?currentRows.map(c=>`<article class="list-row case-list-row"><div><strong>${escapeHtml(displayNumber(c))}</strong><div class="muted">${escapeHtml(c.caseSubtype||labelOf(CASE_TYPES,c.caseType))} · ${escapeHtml(labelOf(DEGREES,c.degree))} · ${escapeHtml(courtMap.get(Number(c.courtId))||'—')}</div><p class="muted">${escapeHtml(c.subject||'لا يوجد موضوع مسجل')}</p></div><div class="row-actions"><a class="primary-button" href="#/cases?id=${c.id}&view=360">فتح الملف</a><button class="secondary-button" data-edit-case="${c.id}">تعديل</button><button class="danger-button" data-archive-case="${c.id}">أرشفة</button></div></article>`).join(''):emptyState('لا توجد قضايا مطابقة.');
    page.querySelector('#casePageInfo').textContent=q||type||status?`نتائج محدودة: ${currentRows.length}`:`الصفحة ${state.pageNumber}`;page.querySelector('#nextCases').disabled=!state.hasMore||Boolean(q||type||status);page.querySelector('#prevCases').disabled=state.pageNumber<=1||Boolean(q||type||status);
  };
  page.querySelector('#addCase').addEventListener('click',()=>showCaseForm(null,()=>renderCaseList(page)));
  search.addEventListener('input',debounce(()=>draw(true),180));typeFilter.addEventListener('change',()=>draw(true));statusFilter.addEventListener('change',()=>draw(true));
  page.querySelector('#nextCases').addEventListener('click',async()=>{if(!state.hasMore)return;history.push({afterKey:state.afterKey,afterPrimaryKey:state.afterPrimaryKey});state.pageNumber+=1;await draw(false);});
  page.querySelector('#prevCases').addEventListener('click',async()=>{const previous=history.pop();if(!previous)return;state.afterKey=previous.afterKey;state.afterPrimaryKey=previous.afterPrimaryKey;state.pageNumber-=1;await draw(false);});
  list.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-case]'),archive=e.target.closest('[data-archive-case]');if(edit){const row=currentRows.find(x=>Number(x.id)===Number(edit.dataset.editCase));if(row)showCaseForm(row,()=>renderCaseList(page));}if(archive)archiveCase(archive.dataset.archiveCase,()=>renderCaseList(page));});
  await draw(true);return()=>{};
}
function relationModal(title,content,onSubmit){const {wrap,close}=modalFrame(title,content);wrap.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',close));wrap.querySelector('form')?.addEventListener('submit',async e=>{e.preventDefault();try{await onSubmit(new FormData(e.currentTarget));close();toast('تم حفظ العلاقة.');location.hash=`#/cases?id=${queryId()}&view=360`;}catch(err){toast(err.message||'تعذر حفظ العلاقة.','error');}});}

async function addClientRelation(caseRow){const clients=await activeRows(STORES.clients);relationModal('ربط عميل بالقضية',`<form><div class="field"><label>العميل *</label><select name="clientId" class="select" required><option value="">اختر العميل</option>${clients.map(c=>`<option value="${c.id}">${escapeHtml(c.fullName)}</option>`).join('')}</select></div><div class="field"><label>صفة العميل</label><select name="role" class="select"><option value="">غير محددة</option>${options(CLIENT_ROLES)}</select></div><label class="check-row"><input type="checkbox" name="isPrimary"><span>العميل الأساسي</span></label><div class="form-actions"><button class="primary-button">حفظ</button><button type="button" class="secondary-button" data-close>إلغاء</button></div></form>`,async fd=>{const clientId=Number(fd.get('clientId')),client=await repo(STORES.clients).get(clientId);if(!client||client.archived)throw new Error('العميل غير موجود أو مؤرشف.');const rows=await repo(STORES.caseClients).all({ limit: 500 });if(rows.some(x=>Number(x.caseId)===Number(caseRow.id)&&Number(x.clientId)===clientId))throw new Error('العميل مرتبط بالقضية بالفعل.');await repo(STORES.caseClients).add({caseId:Number(caseRow.id),clientId,role:String(fd.get('role')||''),isPrimary:fd.get('isPrimary')==='on',notes:'',createdAt:nowISO()});});}
async function addOpponentRelation(caseRow){const opponents=await activeRows(STORES.opponents);relationModal('ربط خصم بالقضية',`<form><div class="field"><label>الخصم/الطرف *</label><select name="opponentId" class="select" required><option value="">اختر الطرف</option>${opponents.map(o=>`<option value="${o.id}">${escapeHtml(o.name)}</option>`).join('')}</select></div><div class="field"><label>الصفة</label><input name="role" class="input" placeholder="مدعى عليه، مستأنف ضده…"></div><div class="form-actions"><button class="primary-button">حفظ</button><button type="button" class="secondary-button" data-close>إلغاء</button></div></form>`,async fd=>{const opponentId=Number(fd.get('opponentId')),o=await repo(STORES.opponents).get(opponentId);if(!o||o.archived)throw new Error('الخصم غير موجود أو مؤرشف.');const rows=await repo(STORES.caseOpponents).all({ limit: 500 });if(rows.some(x=>Number(x.caseId)===Number(caseRow.id)&&Number(x.opponentId)===opponentId))throw new Error('الخصم مرتبط بالقضية بالفعل.');await repo(STORES.caseOpponents).add({caseId:Number(caseRow.id),opponentId,role:String(fd.get('role')||''),notes:'',createdAt:nowISO()});});}
async function addPoaRelation(caseRow){const [poas,clients]=await Promise.all([activeRows(STORES.powerOfAttorneys),activeRows(STORES.clients)]);const cm=new Map(clients.map(c=>[c.id,c.fullName]));relationModal('ربط توكيل بالقضية',`<form><div class="field"><label>التوكيل *</label><select name="poaId" class="select" required><option value="">اختر التوكيل</option>${poas.map(p=>`<option value="${p.id}">${escapeHtml(cm.get(p.clientId)||'عميل غير موجود')} — ${escapeHtml(p.number)}/${escapeHtml(p.year)}</option>`).join('')}</select></div><div class="form-actions"><button class="primary-button">حفظ</button><button type="button" class="secondary-button" data-close>إلغاء</button></div></form>`,async fd=>{const poaId=Number(fd.get('poaId')),p=await repo(STORES.powerOfAttorneys).get(poaId);if(!p||p.archived)throw new Error('التوكيل غير موجود أو مؤرشف.');const rows=await repo(STORES.casePowerOfAttorneys).all({ limit: 500 });if(rows.some(x=>Number(x.caseId)===Number(caseRow.id)&&Number(x.powerOfAttorneyId)===poaId))throw new Error('التوكيل مرتبط بالقضية بالفعل.');if(Number(p.clientId)&&!(await repo(STORES.caseClients).all({ limit: 500 })).some(x=>Number(x.caseId)===Number(caseRow.id)&&Number(x.clientId)===Number(p.clientId)))throw new Error('يجب ربط عميل التوكيل بالقضية أولًا.');await repo(STORES.casePowerOfAttorneys).add({caseId:Number(caseRow.id),powerOfAttorneyId:poaId,notes:'',createdAt:nowISO()});});}
async function addCaseRelation(caseRow){const cases=(await activeRows(STORES.cases)).filter(c=>Number(c.id)!==Number(caseRow.id));relationModal('ربط قضية بقضية أخرى',`<form><div class="field"><label>القضية الأخرى *</label><select name="targetCaseId" class="select" required><option value="">اختر القضية</option>${cases.map(c=>`<option value="${c.id}">${escapeHtml(displayNumber(c))} — ${escapeHtml(c.subject||'')}</option>`).join('')}</select></div><div class="field"><label>نوع العلاقة</label><select name="relationType" class="select">${options(RELATIONS,'related')}</select></div><div class="field"><label>ملاحظات</label><textarea name="notes" class="textarea" rows="2"></textarea></div><div class="form-actions"><button class="primary-button">حفظ</button><button type="button" class="secondary-button" data-close>إلغاء</button></div></form>`,async fd=>{const targetCaseId=Number(fd.get('targetCaseId')),target=await repo(STORES.cases).get(targetCaseId);if(!target||target.archived)throw new Error('القضية الأخرى غير موجودة أو مؤرشفة.');if(targetCaseId===Number(caseRow.id))throw new Error('لا يمكن ربط القضية بنفسها.');const type=String(fd.get('relationType')||'related'),rows=await repo(STORES.caseRelations).all({ limit: 500 });if(rows.some(x=>Number(x.sourceCaseId)===Number(caseRow.id)&&Number(x.targetCaseId)===targetCaseId&&x.relationType===type))throw new Error('هذه العلاقة مسجلة بالفعل.');await repo(STORES.caseRelations).add({sourceCaseId:Number(caseRow.id),targetCaseId,relationType:type,notes:String(fd.get('notes')||'').trim(),createdAt:nowISO()});});}
async function addCaseEvent(caseRow){relationModal('إضافة حدث إلى خط القضية الزمني',`<form><div class="form-grid"><div class="field"><label>نوع الحدث</label><input name="eventType" class="input" value="ملاحظة"></div><div class="field"><label>التاريخ</label><input name="eventDate" class="input" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field full"><label>العنوان *</label><input name="title" class="input" required></div><div class="field full"><label>الوصف</label><textarea name="description" class="textarea" rows="3"></textarea></div></div><div class="form-actions"><button class="primary-button">حفظ</button><button type="button" class="secondary-button" data-close>إلغاء</button></div></form>`,async fd=>{const title=String(fd.get('title')||'').trim();if(!title)throw new Error('عنوان الحدث مطلوب.');await repo(STORES.caseEvents).add({caseId:Number(caseRow.id),eventType:String(fd.get('eventType')||'note').trim(),eventDate:String(fd.get('eventDate')||new Date().toISOString().slice(0,10)),title,description:String(fd.get('description')||'').trim(),sourceType:'caseEvents',sourceId:null,createdAt:nowISO()});});}

async function renderCase360(page,caseId){
  const c=await repo(STORES.cases).get(Number(caseId));if(!c){page.innerHTML=emptyState('القضية المطلوبة غير موجودة.');return()=>{};}
  const caseKey = Number(c.id);
  const byCase = async (store, index='caseId', limit=500, direction='next') => { try { return (await repo(store).page({ index, query: caseKey, limit, direction })).rows; } catch { return []; } };
  const [cr,or,pr,rels,events,hearings,judgments,appeals,tasks,procedures,executions,financial,graph,timeline]=await Promise.all([
    byCase(STORES.caseClients,'caseId'), byCase(STORES.caseOpponents,'caseId'), byCase(STORES.casePowerOfAttorneys,'caseId'),
    byCase(STORES.caseRelations,'sourceCaseId'), byCase(STORES.caseEvents,'caseId',200,'prev'), byCase(STORES.hearings,'caseId',500,'prev'),
    byCase(STORES.judgments,'caseId',500,'prev'), byCase(STORES.appeals,'caseId',500,'prev'), byCase(STORES.caseTasks,'caseId',500),
    byCase(STORES.procedures,'caseId',500,'prev'), byCase(STORES.executionFiles,'caseId',500), byCase(STORES.financialRecords,'caseId',500,'prev'),
    buildCaseGraph(caseKey,{depth:2,maxNodes:80}), getCaseTimeline(caseKey,{limit:120})
  ]);
  const targetRelations = await byCase(STORES.caseRelations,'targetCaseId');
  const clientIds = [...new Set(cr.map(x=>Number(x.clientId)).filter(Boolean))];
  const opponentIds = [...new Set(or.map(x=>Number(x.opponentId)).filter(Boolean))];
  const poaIds = [...new Set(pr.map(x=>Number(x.powerOfAttorneyId)).filter(Boolean))];
  const [clients,opponents,poaRows,courts] = await Promise.all([
    Promise.all(clientIds.slice(0,500).map(id=>repo(STORES.clients).get(id))).then(rows=>rows.filter(Boolean)),
    Promise.all(opponentIds.slice(0,500).map(id=>repo(STORES.opponents).get(id))).then(rows=>rows.filter(Boolean)),
    Promise.all(poaIds.slice(0,500).map(id=>repo(STORES.powerOfAttorneys).get(id))).then(rows=>rows.filter(Boolean)),
    c.courtId ? repo(STORES.courtsAuthorities).get(Number(c.courtId)).then(x=>x?[x]:[]) : Promise.resolve([])
  ]);
  const rs=[...rels,...targetRelations];
  const cls=cr,ops=or,ps=pr,evs=events.sort((a,b)=>String(b.eventDate||b.createdAt).localeCompare(String(a.eventDate||a.createdAt))),hs=hearings.sort((a,b)=>String(b.date).localeCompare(String(a.date))),js=judgments.sort((a,b)=>String(b.date).localeCompare(String(a.date))),aps=appeals,ts=tasks,prs=procedures.sort((a,b)=>String(b.date).localeCompare(String(a.date))),exs=executions,fins=financial;
  page.innerHTML=`<div class="case-detail"><section class="card case-hero"><div><a class="back-link" href="#/cases">← القضايا</a><span class="eyebrow">ملف القضية</span><h2>${escapeHtml(displayNumber(c))}</h2><p class="muted">${escapeHtml(c.subject||'لا يوجد موضوع مسجل')}</p></div><div class="hero-actions"><button id="editCase" class="secondary-button">تعديل</button><button id="archiveCase" class="danger-button">أرشفة</button></div></section>
  <section class="card"><div class="case-facts"><div><span>النوع</span><strong>${escapeHtml(labelOf(CASE_TYPES,c.caseType))}</strong></div><div><span>الدرجة</span><strong>${escapeHtml(labelOf(DEGREES,c.degree))}</strong></div><div><span>الحالة</span><strong>${escapeHtml(labelOf(STATUSES,c.status))}</strong></div><div><span>المحكمة/الجهة</span><strong>${escapeHtml(courtName(courts,c.courtId))}</strong></div><div><span>الدائرة</span><strong>${escapeHtml(c.chamber||'—')}</strong></div><div><span>تاريخ القيد</span><strong>${escapeHtml(formatDate(c.filingDate))}</strong></div></div></section>
  <div class="grid grid-2">
  <section class="card"><div class="section-title"><div><h2>العملاء</h2><p class="muted">العلاقات المسجلة</p></div><button class="secondary-button" id="addClientRelation">＋ ربط عميل</button></div>${cls.length?`<div class="work-list">${cls.map(r=>`<a class="work-item" href="#/clients?id=${r.clientId}&view=360"><div><strong>${escapeHtml(clientName(clients,r.clientId))}</strong><span class="badge">${escapeHtml(r.role||'صفة غير محددة')}${r.isPrimary?' · أساسي':''}</span></div></a>`).join('')}</div>`:emptyState('لا يوجد عميل مرتبط بالقضية.')}</section>
  <section class="card"><div class="section-title"><div><h2>الخصوم</h2><p class="muted">العلاقات المسجلة</p></div><button class="secondary-button" id="addOpponentRelation">＋ ربط خصم</button></div>${ops.length?`<div class="work-list">${ops.map(r=>`<a class="work-item" href="#/opponents"><div><strong>${escapeHtml(opponentName(opponents,r.opponentId))}</strong><span class="badge">${escapeHtml(r.role||'صفة غير محددة')}</span></div></a>`).join('')}</div>`:emptyState('لا يوجد خصوم مرتبطون بالقضية.')}</section>
  <section class="card"><div class="section-title"><div><h2>التوكيلات</h2><p class="muted">العلاقات المسجلة</p></div><button class="secondary-button" id="addPoaRelation">＋ ربط توكيل</button></div>${ps.length?`<div class="work-list">${ps.map(r=>{const p=poas.find(x=>Number(x.id)===Number(r.powerOfAttorneyId));return `<a class="work-item" href="#/clients?id=${p?.clientId||''}&view=360"><div><strong>${escapeHtml(p?`${p.number}/${p.year}`:'توكيل غير موجود')}</strong><span class="badge">${escapeHtml(p?.type||'')}</span></div></a>`}).join('')}</div>`:emptyState('لا توجد توكيلات مرتبطة بالقضية.')}</section>
  <section class="card"><div class="section-title"><div><h2>القضايا المرتبطة</h2><p class="muted">علاقات مسجلة فقط</p></div><button class="secondary-button" id="addCaseRelation">＋ ربط قضية</button></div>${rs.length?`<div class="work-list">${rs.map(r=>{const id=Number(r.sourceCaseId)===Number(c.id)?r.targetCaseId:r.sourceCaseId;return `<a class="work-item" href="#/cases?id=${id}&view=360"><div><strong>قضية #${id}</strong><span class="badge">${escapeHtml(labelOf(RELATIONS,r.relationType))}</span><p class="muted">${escapeHtml(r.notes||'')}</p></div></a>`}).join('')}</div>`:emptyState('لا توجد علاقات قضائية مسجلة.')}</section></div>
  <section class="card"><div class="section-title"><div><h2>الخط الزمني الموحد</h2><p class="muted">عرض تشغيلي مجمع من الأحداث والجلسات والإجراءات والأحكام والطعون والإعلانات والتنفيذ والمتابعات وغيرها.</p></div><button class="secondary-button" id="addCaseEvent">＋ إضافة حدث</button></div>${timeline.items.length?`<div class="case-timeline">${timeline.items.map(e=>`<article class="case-timeline-item"><div class="case-timeline-marker"></div><div class="case-timeline-main"><div class="case-timeline-meta"><span class="badge">${escapeHtml(e.typeLabel)}</span><time>${escapeHtml(formatDate(e.date))}</time></div><strong>${escapeHtml(e.title)}</strong>${e.description?`<p class="muted">${escapeHtml(e.description)}</p>`:''}</div></article>`).join('')}</div>`:emptyState('لا توجد أحداث أو أعمال زمنية مسجلة للقضية.')}${timeline.truncated?'<p class="muted timeline-limit-note">تم عرض جزء محدود من السجل حفاظًا على الأداء. افتح تفاصيل الوحدات المتخصصة لمراجعة البيانات كاملة.</p>':''}</section>
  <section class="card"><div class="section-title"><div><h2>خريطة علاقات القضايا</h2><p class="muted">توسع محدود حتى مستويين من العلاقات المسجلة، دون مسح قاعدة البيانات بالكامل.</p></div></div>${renderCaseGraph(graph,escapeHtml)}</section>
  <div class="grid grid-2"><section class="card"><h2>الجلسات</h2>${hs.length?`<div class="work-list">${hs.slice(0,10).map(h=>`<a class="work-item" href="#/hearings"><div><strong>${escapeHtml(formatDate(h.date))} ${escapeHtml(h.time||'')}</strong><span class="badge">${escapeHtml(h.type||'جلسة')}</span></div><p>${escapeHtml(h.result||'نتيجة غير مسجلة')}</p></a>`).join('')}</div>`:emptyState('لا توجد جلسات مرتبطة بعد.')}</section>
  <section class="card"><h2>الأحكام</h2>${js.length?`<div class="work-list">${js.map(j=>`<a class="work-item" href="#/judgments"><div><strong>${escapeHtml(j.number||'حكم')}</strong><span class="badge">${escapeHtml(formatDate(j.date))}</span></div><p>${escapeHtml(j.summary||j.description||'')}</p></a>`).join('')}</div>`:emptyState('لا توجد أحكام مرتبطة بعد.')}</section>
  <section class="card"><h2>الطعون</h2>${aps.length?`<div class="work-list">${aps.map(a=>`<a class="work-item" href="#/appeals"><div><strong>${escapeHtml(a.number||'طعن')}</strong><span class="badge">${escapeHtml(a.type||'')}</span></div></a>`).join('')}</div>`:emptyState('لا توجد طعون مرتبطة بعد.')}</section>
  <section class="card"><h2>الإجراءات والمهام</h2>${prs.length||ts.length?`<div class="work-list">${prs.slice(0,5).map(p=>`<a class="work-item" href="#/cases"><div><span class="badge">إجراء</span><strong>${escapeHtml(p.description||p.type||'إجراء')}</strong></div><time>${escapeHtml(formatDate(p.date))}</time></a>`).join('')}${ts.slice(0,5).map(t=>`<a class="work-item" href="#/tasks"><div><span class="badge">مهمة</span><strong>${escapeHtml(t.title)}</strong></div><time>${escapeHtml(t.dueDate||'')}</time></a>`).join('')}</div>`:emptyState('لا توجد إجراءات أو مهام مرتبطة.')}</section>
  <section class="card"><h2>التنفيذ</h2>${exs.length?`<div class="work-list">${exs.map(e=>`<a class="work-item" href="#/execution"><div><strong>${escapeHtml(e.executionNumber||'ملف تنفيذ')}</strong><span class="badge">${escapeHtml(e.status||'')}</span></div></a>`).join('')}</div>`:emptyState('لا توجد ملفات تنفيذ مرتبطة.')}</section>
  <section class="card"><h2>المركز المالي</h2>${fins.length?`<div class="work-list">${fins.slice(0,10).map(f=>`<div class="work-item"><div><strong>${escapeHtml(f.description||f.type||'حركة مالية')}</strong><span class="badge">${escapeHtml(f.direction||'')}</span></div><time>${escapeHtml(String(f.amountMinor??''))} ${escapeHtml(f.currency||'EGP')}</time></div>`).join('')}</div>`:emptyState('لا توجد حركات مالية مرتبطة.')}</section></div></div>`;
  page.querySelector('#editCase').addEventListener('click',()=>showCaseForm(c,()=>renderCase360(page,c.id)));page.querySelector('#archiveCase').addEventListener('click',()=>archiveCase(c.id,()=>{location.hash='#/cases';}));page.querySelector('#addClientRelation').addEventListener('click',()=>addClientRelation(c));page.querySelector('#addOpponentRelation').addEventListener('click',()=>addOpponentRelation(c));page.querySelector('#addPoaRelation').addEventListener('click',()=>addPoaRelation(c));page.querySelector('#addCaseRelation').addEventListener('click',()=>addCaseRelation(c));page.querySelector('#addCaseEvent').addEventListener('click',()=>addCaseEvent(c));return()=>{};
}

export async function renderCases(page){const id=queryId();return id&&queryView()==='360'?renderCase360(page,id):renderCaseList(page);}
