import {isActive} from '../core/utils.js';
import { repo } from '../db/repositories.js';
import { STORES } from '../core/constants.js';
import { toISODate, toDate, addDays } from '../core/dates.js';
import { ensureRuleSet, requireRuleMetadata } from './rule-metadata.js';

const VERSION='2026-09-24-verified';
const SOURCE_URL='https://manshurat.org/node/7274';
const RULES=Object.freeze([
  {ruleId:'egypt-admin-cancellation-60',name:'ميعاد رفع دعوى الإلغاء',category:'administrative-cancellation',jurisdiction:'Egypt',effectiveFrom:'1972-10-05',effectiveTo:null,duration:60,unit:'days',startRule:'publication-or-notification-of-decision-or-legally-determined-start',firstDayRule:'rule-specific-review-required',lastDayRule:'include-last-day-subject-to-procedural-review',holidayRule:'not-automatically-applied',weekendRule:'none',sourceType:'legislation', source:'قانون مجلس الدولة رقم 47 لسنة 1972',sourceReference:'قانون مجلس الدولة رقم 47 لسنة 1972 — المادة 24',sourceUrl:SOURCE_URL,notes:'المادة 24 تقرر ستين يوماً لرفع دعوى الإلغاء من النشر أو إعلان صاحب الشأن بالقرار، مع أحكام خاصة بالتظلم. البرنامج لا يستنتج تاريخ بدء الميعاد ولا مدى وجوب التظلم.',active:true,version:VERSION,verificationDate:'2026-09-24'},
  {ruleId:'egypt-admin-grievance-decision-60',name:'مدة البت في التظلم الإداري',category:'administrative-grievance',jurisdiction:'Egypt',effectiveFrom:'1972-10-05',effectiveTo:null,duration:60,unit:'days',startRule:'date-of-grievance',firstDayRule:'rule-specific-review-required',lastDayRule:'include-last-day-subject-to-procedural-review',holidayRule:'not-automatically-applied',weekendRule:'none',sourceType:'legislation', source:'قانون مجلس الدولة رقم 47 لسنة 1972',sourceReference:'قانون مجلس الدولة رقم 47 لسنة 1972 — المادة 24',sourceUrl:SOURCE_URL,notes:'المادة 24 تتناول مدة البت في التظلم وآثار مضيها. يجب التحقق من قابلية القرار للتظلم وطبيعته قبل التطبيق.',active:true,version:VERSION,verificationDate:'2026-09-24'},
  {ruleId:'egypt-admin-grievance-lawsuit-60',name:'ميعاد رفع الدعوى بعد التظلم',category:'administrative-grievance',jurisdiction:'Egypt',effectiveFrom:'1972-10-05',effectiveTo:null,duration:60,unit:'days',startRule:'end-of-sixty-day-grievance-decision-period-or-date-of-rejection',firstDayRule:'rule-specific-review-required',lastDayRule:'include-last-day-subject-to-procedural-review',holidayRule:'not-automatically-applied',weekendRule:'none',sourceType:'legislation', source:'قانون مجلس الدولة رقم 47 لسنة 1972',sourceReference:'قانون مجلس الدولة رقم 47 لسنة 1972 — المادة 24',sourceUrl:SOURCE_URL,notes:'هذه قاعدة مركبة؛ يجب تحديد تاريخ الرفض الصريح أو انتهاء مدة البت في التظلم وفق الوقائع قبل إدخال تاريخ البداية.',active:true,version:VERSION,verificationDate:'2026-09-24'}
]);
function parse(v){const d=toDate(v);return d&&!Number.isNaN(d.getTime())?d:null;}
export async function ensureAdministrativeRules(){await ensureRuleSet(RULES);}
export async function listAdministrativeRules(){const rows=await repo(STORES.legalRules).all({ limit: 500 });return rows.filter(x=>isActive(x)&&String(x.ruleId||'').startsWith('egypt-admin-')).sort((a,b)=>String(a.name).localeCompare(String(b.name),'ar'));}
export async function calculateAdministrativeDeadline({ruleId,startDate,caseId=null,notes=''}){const start=parse(startDate);if(!start)throw new Error('أدخل تاريخ بداية صحيحاً.');const rule=await repo(STORES.legalRules).get(Number(ruleId));if(!rule||!String(rule.ruleId).startsWith('egypt-admin-'))throw new Error('القاعدة الإدارية غير موجودة.');requireRuleMetadata(rule);const deadline=addDays(start,Number(rule.duration));const warnings=['الحساب أداة مساعدة ولا يحسم بذاته قبول الدعوى أو فوات الميعاد.','لم يستنتج البرنامج تاريخ البداية؛ يجب إثبات الواقعة المنشئة للميعاد ومراجعة النصوص الخاصة وطريقة الإعلان والتظلم.'];if(rule.ruleId==='egypt-admin-cancellation-60')warnings.push('المادة 24 ترتبط بالنشر أو إعلان صاحب الشأن، وقد توجد قواعد خاصة لطبيعة القرار أو التظلم.');if(rule.ruleId==='egypt-admin-grievance-lawsuit-60')warnings.push('تاريخ البداية يجب أن يكون تاريخ الرفض الصريح أو التاريخ القانوني الناتج عن انتهاء مدة البت في التظلم بعد التحقق من الوقائع.');return {ruleId:rule.id,ruleKey:rule.ruleId,ruleVersion:rule.version,ruleName:rule.name,startDate:toISODate(start),duration:Number(rule.duration),unit:rule.unit,deadline:toISODate(deadline),calculatedAt:new Date().toISOString(),warnings,assumptions:[rule.firstDayRule,rule.lastDayRule,rule.holidayRule],sourceReference:rule.sourceReference,sourceUrl:rule.sourceUrl,caseId:caseId?Number(caseId):null,notes};}
export async function saveAdministrativeCalculation(result){return repo(STORES.calculationHistory).add({calculatorType:'administrative-deadline',caseId:result.caseId||null,ruleId:result.ruleId,ruleVersion:result.ruleVersion,inputs:{startDate:result.startDate,duration:result.duration,unit:result.unit},result:{deadline:result.deadline},warnings:result.warnings,assumptions:result.assumptions,calculatedAt:result.calculatedAt,notes:result.notes||''});}
export {RULES};
